version: '3.9'

services:
  flaskapp-node:
    build: ./backend
    ports:
      - "8082:8080"
    volumes:
      - ./backend:/app
    networks:
      app_network:
        ipv4_address: 10.0.1.2

  vueapp-node:
    build: ./frontend
    ports:
      - "8083:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      app_network:
        ipv4_address: 10.0.1.3

  playwright-e2e:
    image: mcr.microsoft.com/playwright:v1.40.0-jammy
    volumes:
      - ./e2e:/app
      - /app/node_modules
    environment:
      - CI=true
    working_dir: /app
    command: sh -c "npm install && npm run test:e2e"
    networks:
      app_network:
        ipv4_address: 10.0.1.4

networks:
  app_network:
    ipam:
      config:
        - subnet: 10.0.1.0/24

#volumes:
#  backend:
#  frontend: