version: '3.8'

services:
  flaskapp-node:
    build: ./backend
    ports:
      - "8082:8080"
    volumes:
      - ./backend:/app
    networks:
      app_network:
        ipv4_address: 10.0.1.2

  vueapp-node:
    build: ./frontend
    ports:
      - "8083:8080"
    volumes:
      - ./frontend:/app
    networks:
      app_network:
        ipv4_address: 10.0.1.3

networks:
  app_network:
    ipam:
      config:
        - subnet: 10.0.1.0/24

volumes:
  backend:
  frontend: